export const SHOW_AUTHORIZATION_MESSAGE = 'APP/SHOW_AUTHORIZATION_MESSAGE';
export const HIDE_AUTHORIZATION_COMPONENT = 'APP/HIDE_AUTHORIZATION_COMPONENT';
export const SHOW_AUTHORIZATION_ERROR_MODAL = 'APP/SHOW_AUTHORIZATION_ERROR_MODAL';
export const HIDE_AUTHORIZATION_ERROR_MODAL = 'APP/HIDE_AUTHORIZATION_ERROR_MODAL';

export const ADD_AVATAR = 'DATA/ADD_AVATAR';
export const ADD_TERMINAL = 'DATA/ADD_TERMINAL';
export const DELETE_TERMINAL = 'DATA/DELETE_TERMINAL';